[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "auraflux-core"
version = "0.3.0"
authors = [
    { name = "Scott Huang", email = "shangyuhuang@gmail.com" },
]
description = "The core AI agent package for the Auraflux project, built to solve AI knowledge fragmentation."
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = [
    "chardet==7.6.0",
    "google-genai==1.64.0",
    "networkx==3.6.1",
    "numpy==2.4.3",
    "openai==2.23.0",
    "opensearch-py==3.2.0",
    "pydantic==2.12.5",
    "pydantic-settings==2.13.1",
    "pygraphviz==1.14",
    "tenacity==9.1.4"
]

[project.urls]
Homepage = "https://github.com/solarfresh/Auraflux-Core"
Issues = "https://github.com/solarfresh/Auraflux-Core/issues"

[tool.pytest.ini_options]
addopts = "--cov=src --cov-report=term --cov-report=html"
python_files = ["tests.py", "test_*.py", "*_tests.py"]
pythonpath = ["src"]
