import json
from unittest.mock import AsyncMock, MagicMock

import pytest

from auraflux_core.core.schemas.pipelines import ValidationResult
from auraflux_core.rag.agents.keywords_extractor import ExtractKeywordsAgent


@pytest.fixture
def mock_extract_keywords_agent(mock_agent_config, mock_client_manager):
    """
    Fixture providing an ExtractKeywordsAgent instance configured
    using standard conftest fixtures.
    """
    agent = ExtractKeywordsAgent(
        config=mock_agent_config,
        client_manager=mock_client_manager
    )
    # Mock internal tool_executor to isolate agent logic from actual tools
    agent.tool_executor = MagicMock()
    agent.tool_executor.run = AsyncMock()
    return agent


@pytest.mark.asyncio
async def test_process_incremental_triples_success_with_flagged_data(
    mock_extract_keywords_agent
):
    """
    Test Case 1: Verify state updates when ExtractKeywordsAgent handles flagged triples.
    Ensures clean_triples, flagged_triples, and flagged_reasons are populated.
    """
    # 1. Arrange
    plan_output = {
        "triples": [
            {"subject": "it", "predicate": "has_value", "object": "100"},
            {"subject": "Apple", "predicate": "located_in", "object": "USA"}
        ]
    }

    processor_res = MagicMock(content=plan_output["triples"])
    checker_payload = {
        "has_flagged": True,
        "clean_triples": [
            {"subject": "Apple", "predicate": "located_in", "object": "USA"}
        ],
        "flagged_triples": [
            {
                "subject": "it",
                "predicate": "has_value",
                "object": "100",
                "_flag_reasons": ["Missing subject_resolved for anaphoric pronoun 'it'"]
            }
        ]
    }
    checker_res = MagicMock(content=json.dumps(checker_payload))

    # Configure mock responses for sequential tool calls
    mock_extract_keywords_agent.tool_executor.run.side_effect = [
        processor_res,
        checker_res
    ]

    # 2. Act
    has_flagged, reasons, check_data = await mock_extract_keywords_agent._process_incremental_triples(
        payload={},
        plan_output=plan_output
    )

    # 3. Assert
    assert has_flagged is True
    assert len(reasons) == 1
    assert reasons[0] == "Missing subject_resolved for anaphoric pronoun 'it'"
    assert check_data == checker_payload

@pytest.mark.asyncio
async def test_process_incremental_triples_deduplication(
    mock_extract_keywords_agent
):
    """
    Test Case 2: Verify that clean triples are properly deduplicated and updated
    based on the (subject, predicate, object) tuple identity across passes.
    """
    # 1. Arrange
    plan_output = {
        "_accumulated_clean_triples": [
            {"subject": "Apple", "predicate": "located_in", "object": "USA", "version": 1}
        ],
        "triples": [
            {"subject": "Apple", "predicate": "located_in", "object": "USA", "version": 2}
        ]
    }

    processor_res = MagicMock(content=plan_output["triples"])
    checker_payload = {
        "has_flagged": False,
        "clean_triples": [
            {"subject": "Apple", "predicate": "located_in", "object": "USA", "version": 2}
        ],
        "flagged_triples": []
    }
    checker_res = MagicMock(content=json.dumps(checker_payload))

    mock_extract_keywords_agent.tool_executor.run.side_effect = [
        processor_res,
        checker_res
    ]

    # 2. Act
    has_flagged, reasons, check_data = await mock_extract_keywords_agent._process_incremental_triples(
        payload={},
        plan_output=plan_output
    )

    # 3. Assert
    assert has_flagged is False
    assert len(reasons) == 0
    assert check_data["clean_triples"][0]["version"] == 2

@pytest.mark.asyncio
async def test_incremental_triples_total_count_and_deduplication(
    mock_extract_keywords_agent
):
    """
    Test dedicated to verifying that incremental triple processing and merging:
    1. Correctly updates existing triples in-place (without inflating the count).
    2. Correctly appends distinct new triples.
    3. Maintains accurate total triple counts across _accumulated_clean_triples and candidate triples.
    """
    # 1. Arrange
    # Initial state: Contains 2 previously accumulated clean triples
    initial_accumulated = [
        {"subject": "Apple", "predicate": "located_in", "object": "USA", "version": 1},
        {"subject": "Microsoft", "predicate": "located_in", "object": "USA", "version": 1}
    ]

    # Incoming candidate triples generated by LLM/Pipeline:
    # - 1 updated version of an existing triple (Apple, version 2)
    # - 1 entirely new distinct triple (Google)
    incoming_candidates = [
        {"subject": "Apple", "predicate": "located_in", "object": "USA", "version": 2},
        {"subject": "Google", "predicate": "located_in", "object": "USA", "version": 1}
    ]

    plan_output = {
        "_accumulated_clean_triples": initial_accumulated,
        "triples": incoming_candidates
    }

    # Configure tool executor mock responses (triple_processor & triple_rule_checker)
    processor_res = MagicMock(content=incoming_candidates)
    checker_payload = {
        "has_flagged": False,
        "clean_triples": incoming_candidates,
        "flagged_triples": []
    }
    checker_res = MagicMock(content=json.dumps(checker_payload))

    mock_extract_keywords_agent.tool_executor.run.side_effect = [
        processor_res,
        checker_res
    ]

    # 2. Act: Step 1 Inspection
    has_flagged, reasons, check_data = await mock_extract_keywords_agent._process_incremental_triples(
        payload={},
        plan_output=plan_output
    )

    validation_result = ValidationResult(
        is_valid=not has_flagged,
        reasons=reasons,
        metadata={
            "check_data": check_data,
            "clean_triples": check_data.get("clean_triples", []),
            "flagged_triples": check_data.get("flagged_triples", [])
        }
    )

    # 3. Act: Step 2 Refinement Merge
    refined_plan = {"triples": incoming_candidates}
    merged_plan = mock_extract_keywords_agent.merge_refined_plan(
        payload={},
        current_plan=plan_output,
        refined_plan=refined_plan,
        validation_result=validation_result
    )

    # 4. Assert: Total counts and deduplication verification
    # Expected behavior:
    # 2 initial triples + 1 in-place update (Apple v2) + 1 new append (Google) = EXACTLY 3 triples.
    # Count should not inflate or produce duplicate keys.
    EXPECTED_TOTAL_COUNT = 3

    assert len(merged_plan["_accumulated_clean_triples"]) == EXPECTED_TOTAL_COUNT
    assert len(merged_plan["triples"]) == EXPECTED_TOTAL_COUNT

    # Verify in-place update for key matching (Apple v1 -> v2)
    apple_triple = next(
        t for t in merged_plan["triples"]
        if (t.get("subject"), t.get("predicate"), t.get("object")) == ("Apple", "located_in", "USA")
    )
    assert apple_triple["version"] == 2

    # Verify all expected subjects are present
    all_subjects = {t["subject"] for t in merged_plan["triples"]}
    assert all_subjects == {"Apple", "Microsoft", "Google"}

@pytest.mark.asyncio
async def test_incremental_triples_count_with_flagged_repair(
    mock_extract_keywords_agent
):
    """
    Test dedicated to verifying triple count integrity when a flagged triple is repaired during a refinement pass.
    """
    # 1. Arrange
    plan_output = {
        "triples": [
            {"subject": "it", "predicate": "has_value", "object": "100"},
            {"subject": "Apple", "predicate": "located_in", "object": "USA"}
        ]
    }

    processor_res = MagicMock(content=plan_output["triples"])
    checker_payload = {
        "has_flagged": True,
        "clean_triples": [
            {"subject": "Apple", "predicate": "located_in", "object": "USA"}
        ],
        "flagged_triples": [
            {
                "subject": "it",
                "predicate": "has_value",
                "object": "100",
                "_flag_reasons": ["Missing pronoun resolution for subject 'it'"]
            }
        ]
    }
    checker_res = MagicMock(content=json.dumps(checker_payload))

    mock_extract_keywords_agent.tool_executor.run.side_effect = [
        processor_res,
        checker_res
    ]

    # Act 1: Initial Inspection (1 clean triple, 1 flagged triple)
    has_flagged, reasons, check_data = await mock_extract_keywords_agent._process_incremental_triples(
        payload={},
        plan_output=plan_output
    )

    validation_result = ValidationResult(
        is_valid=not has_flagged,
        reasons=reasons,
        metadata={
            "check_data": check_data,
            "clean_triples": check_data.get("clean_triples", []),
            "flagged_triples": check_data.get("flagged_triples", [])
        }
    )

    # Act 2: LLM Refinement repair pass (resolving "it" to "Apple Inc.")
    repaired_refined_plan = {
        "triples": [
            {"subject": "Apple Inc.", "predicate": "has_value", "object": "100"}
        ]
    }

    merged_plan = mock_extract_keywords_agent.merge_refined_plan(
        payload={},
        current_plan=plan_output,
        refined_plan=repaired_refined_plan,
        validation_result=validation_result
    )

    # Assert Count:
    # 1 verified clean triple (Apple located_in USA) + 1 repaired candidate triple (Apple Inc. has_value 100) = 2 triples total.
    assert len(merged_plan["_accumulated_clean_triples"]) == 1
    assert len(merged_plan["triples"]) == 2
